---
- name: Clone Django repository and deploy application
  hosts: app
  become: yes
  vars:
    repo_url: https://github.com/mdn/django-locallibrary-tutorial
    repo_dest: /opt/django-locallibrary-tutorial
    docker_image: timurbabs/django

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone Django repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        clone: yes
        update: yes
      register: git_clone

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Django application container
      docker_container:
        name: django-app
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
        volumes:
          - "{{ repo_dest }}:/app"
      register: container_result

    - name: Display container status
      debug:
        msg: "Django application is running on port 8000"
      when: container_result is succeeded
