---
- name: Clone Django repository and deploy application
  hosts: app
  become: yes
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone Django repository
      git:
        repo: "{{ django_repo }}"
        dest: "{{ django_dest }}"
        clone: yes
        update: yes
      register: git_clone

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Django application container
      docker_container:
        name: django-app
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:8000"
        volumes:
          - "{{ django_dest }}:/app"
      register: container_result

    - name: Display container status
      debug:
        msg: "Django application is running on port {{ app_port }}"
      when: container_result is succeeded
