[app]
192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=/home/doul_sy/.ssh/vagrant_lab6/app_key

[monitoring]
192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=/home/doul_sy/.ssh/vagrant_lab6/monitoring_key
