---
all:
  children:
    app:
      hosts:
        app:
          ansible_host: 192.168.56.20
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/doul_sy/.ssh/vagrant_keys/app_private_key

    postgresql_servers:
      hosts:
        db:
          ansible_host: 192.168.56.21
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/doul_sy/.ssh/vagrant_keys/db_private_key
          postgresql_role: master
          postgresql_replication: false
