---
- hosts: localhost
  become: yes
  tasks:
    - name: Install OpenVPN and dependencies
      apt:
        name:
          - openvpn
          - easy-rsa
          - openssl
        state: present

    - name: Create OpenVPN directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/openvpn
        - /etc/openvpn/server
        - /etc/openvpn/client

    - name: Copy EasyRSA vars file for non-interactive operation
      copy:
        content: |
          set_var EASYRSA_REQ_COUNTRY    "US"
          set_var EASYRSA_REQ_PROVINCE   "California"
          set_var EASYRSA_REQ_CITY       "San Francisco"
          set_var EASYRSA_REQ_ORG        "OpenVPN"
          set_var EASYRSA_REQ_EMAIL      "admin@example.com"
          set_var EASYRSA_REQ_OU         "IT"
          set_var EASYRSA_KEY_SIZE       2048
          set_var EASYRSA_ALGO           rsa
          set_var EASYRSA_CA_EXPIRE      3650
          set_var EASYRSA_CERT_EXPIRE    365
        dest: /etc/openvpn/vars
        mode: '0644'

    - name: Initialize PKI
      command: /usr/share/easy-rsa/easyrsa --batch init-pki
      args:
        chdir: /etc/openvpn
        creates: /etc/openvpn/pki

    - name: Generate CA certificate non-interactively
      command: /usr/share/easy-rsa/easyrsa --batch build-ca nopass
      args:
        chdir: /etc/openvpn
        creates: /etc/openvpn/pki/ca.crt

    - name: Generate server certificate
      command: /usr/share/easy-rsa/easyrsa --batch gen-req server nopass
      args:
        chdir: /etc/openvpn
        creates: /etc/openvpn/pki/reqs/server.req

    - name: Sign server certificate
      command: /usr/share/easy-rsa/easyrsa --batch sign-req server server
      args:
        chdir: /etc/openvpn
        creates: /etc/openvpn/pki/issued/server.crt

    - name: Generate Diffie-Hellman parameters
      command: /usr/share/easy-rsa/easyrsa --batch gen-dh
      args:
        chdir: /etc/openvpn
        creates: /etc/openvpn/pki/dh.pem

    - name: Copy server configuration
      copy:
        content: |
          port 1194
          proto udp
          dev tun
          ca /etc/openvpn/pki/ca.crt
          cert /etc/openvpn/pki/issued/server.crt
          key /etc/openvpn/pki/private/server.key
          dh /etc/openvpn/pki/dh.pem
          server 10.8.0.0 255.255.255.0
          push "redirect-gateway def1 bypass-dhcp"
          push "dhcp-option DNS 8.8.8.8"
          keepalive 10 120
          cipher AES-256-CBC
          persist-key
          persist-tun
          status /var/log/openvpn-status.log
          verb 3
        dest: /etc/openvpn/server.conf
        mode: '0644'

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Generate client certificate
      command: /usr/share/easy-rsa/easyrsa --batch gen-req client1 nopass
      args:
        chdir: /etc/openvpn
        creates: /etc/openvpn/pki/reqs/client1.req

    - name: Sign client certificate
      command: /usr/share/easy-rsa/easyrsa --batch sign-req client client1
      args:
        chdir: /etc/openvpn
        creates: /etc/openvpn/pki/issued/client1.crt

    - name: Create client OVPN file
      copy:
        content: |
          client
          dev tun
          proto udp
          remote localhost 1194
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          verb 3
          <ca>
          {{ lookup('file', '/etc/openvpn/pki/ca.crt') }}
          </ca>
          <cert>
          {{ lookup('file', '/etc/openvpn/pki/issued/client1.crt') }}
          </cert>
          <key>
          {{ lookup('file', '/etc/openvpn/pki/private/client1.key') }}
          </key>
        dest: /etc/openvpn/client/client1.ovpn
        mode: '0644'

    - name: Start OpenVPN service
      systemd:
        name: openvpn@server
        state: started
        enabled: yes

    - name: Verify OVPN file creation
      stat:
        path: /etc/openvpn/client/client1.ovpn
      register: ovpn_file

    - name: Display success message
      debug:
        msg: |
          OpenVPN server deployed successfully!
          Client configuration: /etc/openvpn/client/client1.ovpn
          OVPN file size: {{ ovpn_file.stat.size }} bytes
