Vagrant.configure("2") do |config|
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/jammy64"
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.20"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    # Provisionnement Ansible pour app
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy_postgresql.yml"
      ansible.groups = {
        "app" => ["app"]
      }
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/jammy64"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.21"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    # Provisionnement Ansible pour db
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy_postgresql.yml"
      ansible.groups = {
        "postgresql_servers" => ["db"],
        "postgresql_master" => ["db"]
      }
      ansible.extra_vars = {
        postgresql_role: "master",
        postgresql_replication: true
      }
    end
  end
end
