---
- name: Configure monitoring server
  hosts: monitoring
  become: yes
  roles:
    - common
    - docker
    - prometheus
    - grafana
    - loki

- name: Configure application server
  hosts: app
  become: yes
  roles:
    - common
    - docker
    - spring_app
